### ISSUE TITLE
Match details

### ISSUE THREAD

**Issue by Mrfull** [ValvePython/dota2#67]
I want to get results(who win or lose) in match, how i can do it?
It's return to me some job_id, but what is it?
`self.dota.request_match_details(match_id)`
And where i can get match_id if i create lobby by

`        
settings = {
    'game_name': lobby_name,
    "game_mode": DOTA_GameMode.DOTA_GAMEMODE_1V1MID,
    "pass_key": "PWA",
}
self.dota.create_practice_lobby(password, settings)
`

**Comment by rossengeorgiev** [comment]
`dota.wait_event(job_id)` to wait for response to that specific request, or to any match details response `wait_event('match_details')`

**Comment by Mrfull** [comment]
So for get this match_details, user witch one play via python code, should be in lobby all time till game will finished?

**Comment by rossengeorgiev** [comment]
I don't understand what you are asking

**Comment by Mrfull** [comment]
I'm asking about, to get information about which team won, you need the bot to be in the match until the end of the game, right?

**Comment by rossengeorgiev** [comment]
No. Just get the match details after the match

**Comment by Mrfull** [comment]
How script can know when match is finished?

**Comment by DEV-ONI** [comment]
Assuming you're waiting for the match to finish and not retrieving details of a public lobby - 

On the lobby event: `EVENT_LOBBY_CHANGED`, 
if the `CSODOTALobby.State` is `POSTGAME`, the protobuf message passed to the event handler will **contain details you want about the match such as the match duration and the winning faction.** The outcome is `k_EMatchOutcome_Unknown` by default until the postgame.

https://github.com/ValvePython/dota2/blob/ca75440adca20d852b9aec3917e4387466848d5b/protobufs/dota_gcmessages_common_match_management.proto#L275

You can create a dispatcher that handles all the lobby states from the `EVENT_LOBBY_CHANGED` event.

**Comment by Mrfull** [comment]
Can you give me some example how to do it for get match results?

**Comment by DEV-ONI** [comment]
Sure friend

Initialize the `Dota2Client`. 
Let's say dota_client here is an instance of `Dota2Client` 

I wrote this in a hurry so hope you can understand

```python

from dota2.common_enums import ESOType
from dota2.features import sharedobjects as so


# get lobby proto
CSODOTALobbyProto = so.find_so_proto(ESOType.CSODOTALobby)
LobbyState = CSODOTALobbyProto.State


# add this callback for event 'lobby_changed'
dota_client.on('lobby_changed', lobby_change_handler)


# lobby state handler dispatch
state_handler_dispatch = dict([
    (LobbyState.UI, #callable here),
    (LobbyState.READYUP, #callable here),
    (LobbyState.NOTREADY, #callable here),
    (LobbyState.SERVERSETUP, #callable here),
    (LobbyState.RUN, #callable here),
    (LobbyState.POSTGAME,  post_game_handler),
    (LobbyState.SERVERASSIGN, #callable)
])


def lobby_change_handler(message):

    logger.info(f"Event: Lobby Change: {message}")
    
   # if message field has state
    if message.HasField('state'):
        # call appropriate handler for lobby state
        state_handler_dispatch[message.state](message)


def post_game_handler(message):
    # protobuf message passed to this callable will contain info about the postgame
    pass

**Comment by Mrfull** [comment]
Thank you very much. If you know can you answer on thats questions:
https://github.com/ValvePython/dota2/issues/68
https://github.com/ValvePython/dota2/issues/69

**Comment by DEV-ONI** [comment]
I made a slight error which I corrected.

Attach the post game handler to `LobbyState.POSTGAME` instead of `LOBBYASSIGN`

**Comment by Mrfull** [comment]
@DEV-ONI I try to use your code and get error. Do you know what is it and how to fix it?

`Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/Users/macbook/PycharmProjects/no25_cybert-test/auth_system/controller_dota2.py", line 112, in lobby_change_handler
    self.state_handler_dispatch[message.state](message)
KeyError: 0
2021-07-10T22:46:06Z <Greenlet at 0x7fdbb0d9d150: <bound method DotaLobbyManager.lobby_change_handler of <__main__.DotaLobbyManager object at 0x7fdbb05780d0>>(lobby_id: 27277905363441853
game_mode: 21
state: U)> failed with KeyError`

**Comment by Mrfull** [comment]
@DEV-ONI If you know can you answer on thats questions:
https://github.com/ValvePython/dota2/issues/68

**Comment by DEV-ONI** [comment]
Can you show me the code for this?
You're getting a KeyError, which means you're attempting to get a key
in `state_handler_dispatch`
that doesn't exist.

**Comment by Mrfull** [comment]
@DEV-ONI 
Thats how its look in my code:


```
class DotaController:
    def  __init__(self):
        self.client = SteamClient()
        self.dota = Dota2Client(self.client)

        # get lobby proto
        CSODOTALobbyProto = so.find_so_proto(ESOType.CSODOTALobby)
        LobbyState = CSODOTALobbyProto.State

        # add this callback for event 'lobby_changed'
        self.dota.on('lobby_changed', self.lobby_change_handler)
        self.client.on('disconnected', self.reconnect_client)

        # lobby state handler dispatch
        self.state_handler_dispatch = dict([
            (LobbyState.UI, self.test),
            (LobbyState.READYUP, self.test),
            (LobbyState.NOTREADY, self.test),
            (LobbyState.SERVERSETUP, self.test),
            (LobbyState.RUN, self.test),
            (LobbyState.POSTGAME, self.post_game_handler),
            (LobbyState.SERVERASSIGN, self.test)
        ])

    def lobby_change_handler(self, message):
        logging.info(f"Event: Lobby Change: {message}")

        # if message field has state
        print("all members: " + str(len(message.all_members)))
        if message.HasField('state'):
            # call appropriate handler for lobby state

            self.state_handler_dispatch[message.state](message)

    def post_game_handler(self, message):
        print("message: " + str(message))
        print("match_outcome: " + str(message.match_outcome))

    def test(self, message):
        logging.info(f"Event: State: {message.state}")
```
